### ISSUE TITLE
Refactor LiftArm with Winch support

### ISSUE THREAD

**Issue by nhubbard** [Robocubs/2018RobotCode#2]
### Within LiftArm Subsystem
* [x] ~~Add~~ Define getArmAngle method
* [x] ~~Add~~ Define resetArmAngle method
* [x] ~~Add~~ Define setArmAngle method
* [x] ~~Add~~ Define getWristAngle method
* [x] ~~Add~~ Define resetWristAngle method
* [x] ~~Add~~ Define setWristAngle method
* [x] ~~Add~~ Define setClamp method
* [x] ~~Add~~ Define engageHook method

### Within Commands
* [x] ~~Add~~ Define PickUpCube command
* [x] ~~Add~~ Define DropOffScaleHigh command
* [x] ~~Add~~ Define DropOffScaleMedium command
* [x] ~~Add~~ Define DropOffScaleLow command
* [x] ~~Add~~ Define DropOffSwitchHigh command
* [x] ~~Add~~ Define DropOffSwitchMedium command
* [x] ~~Add~~ Define DropOffSwitchLow command
* [x] Add Climb command (already created via start and end climb)
* [x] Remove all lift, arm, clamp and hook commands

**Comment by nhubbard** [comment]
@TimAndyOthers Be careful! It's not *complete* until you have some content. The robot code will fail to build until these methods are somehow defined.

**Comment by pguenthe** [comment]
Talking with Jim our command needs are a little different:
- We'll need the robot to get into position before a climb or drop (arm at the right angle etc) so we'll need commands for that.
- We can get away with a single drop on the switch because the platform is never over the height of the sides

Here's the list of commands I'm looking at now:
- PickUpCube
- AssumeScalePosition
- DropOffScaleHigh (we'll probably dump backwards)
- DropOffScaleLow (we'll dump forwards)
- AssumeSwitchPosition
- DropSwitch
- AssumeClimbPosition
- StartClimb
- AbortClimb

Names are open to discussion , but that's the idea now.

**Comment by nhubbard** [comment]
@pguenthe Sounds good, I'll get working after school.

**Comment by pguenthe** [comment]
Check with Jim--when I talked with him Monday it sounded like there isn't a Hook anymore.  (Or rather, the hook's entirely passive.)

**Comment by nhubbard** [comment]
@pguenthe We are currently discussing with Jim what his current plan is to work with the hook. On another note, we also have pneumatic gear shifting working now.

**Comment by noahhusby** [comment]
@nhubbard The hook is the part that grabs the blocks. It is controlled by the pneumatic controller, in the code, it is referred to as the armClamp. Hook == armClamp, so I removed all the hook references and left the armClamp in robot map and lift arm subsystem.

**Comment by nhubbard** [comment]
@noahhusby Good call on closing this. I completely agree.

**Comment by TimAndyOthers** [comment]
The hook was originally the hook to clamp the arm to the chasis once it has finished climbing, not the armclamp. At least when I created it that was the original intention. Also, I don't think I recall setting Hook == armClamp, but I'm not sure

**Comment by noahhusby** [comment]
@Robocubs/2018-programmers, I take back what I said, the hook is the part on top of the wrist, that will pull the robot up. Steven added a DigitalOutput for the hook when it doesn't move at all or need controlling. We just need to move the wrist, to get the hook in position, nothing about the hook moves.
