### ISSUE TITLE
Develop PID-Based Drivetrain Code

### ISSUE THREAD

**Issue by pguenthe** [Robocubs/2018RobotCode#4]
Whether we're basing it on last year's code or not, let's start implementing some PID code for the drivetrain that we can use in autonomous:

* [x] Define `driveForward(Number distance)`
* [x] Define `driveBackward(Number distance)`
* [x] Define `turn(Number angle)` method as a low-level control. These with have to use the angle from the NavX compass.
* [x] Define `turnLeft()` method as high-level interface to `turn(Number angle)` to turn 90° to the left.
* [x] Define `turnRight()` method as high-level interface to `turn(Number angle)` to turn 90° to the right.

The Drivetrain will also need to use the pneumatics to shift gears.  We need to discuss how exactly we want to do this (automatic transmission shifts gears at a set speed?  drive chooses between high and low gear?).  Look for examples of how other teams did it--there should be some good whitepapers and other documentation out there.

**Edit**: Modified list for completion sake. - @nhubbard

**Comment by nhubbard** [comment]
@pguenthe How are we doing multiple gears? The only information I have found is the Super Shifter on AndyMark, but I have no idea how this works.

**Comment by pguenthe** [comment]
@nhubbard you've got some research to do!  The gears are shifted by pneumatics, so each side should have a DoubleSolenoid which you fire one way for one gear, the other way for the other.

I believe we're using the VexPro 3 CIM Ball Shifter but double check with Mr. Wong.  https://www.vexrobotics.com/3cimballshifter.html  In fact, as long as it's operated pneumatically and the right hardware is in place, the code should be hardware-agnostic.

**Comment by nhubbard** [comment]
@pguenthe Makes sense. I was half dreaming of perfectly working vision at the time <sup>**\s**</sup>

**Comment by nhubbard** [comment]
@pguenthe I added PIDSubsystem support in 40736e1c0946e7d0f0cffe1a530fc292210c6963, but I'm having trouble working with it (all it does is provide an interface to PIDController that's tightly integrated with the Subsystem).
Any suggestions?

**Comment by pguenthe** [comment]
Individual methods are going to have to use the PIDController.  Take a look at last year's code (at least the good stuff) and look for tutorials.  I don't think we've used PIDSubsystem before, though maybe we should have.

**Comment by nhubbard** [comment]
@pguenthe We were able to test the robot yesterday. Our current solution (`teleopControl()` in `org.usfirst.frc.team1701.robot.subsystems.DriveTrain`) works very well. Now our current setup is to get the PID value in `returnPIDInput()` and apply it in `usePIDOutput()` (this is the difficult part). We're having some issues in this part, so it would be a good idea to focus on this on Monday.

**Comment by noahhusby** [comment]
@nhubbard @pguenthe, I currently have setHighGear(), and setLowGear(), in DriveTrain.java, as of right now it is controlled by a physical switch on the board and can be called from within the code. Should we, as @pguenthe suggested, make it automatically switch depending on the speed input, both from auto. and from teleop?

**Comment by noahhusby** [comment]
@Robocubs/2018-programmers So... I added an auto gear feature. I also added documentation for auto gear, but here it is better. So I was thinking that we could have a three-way rotary switch on the controller. `Left = Low Gear`, `Right = High Gear`, and `Middle = Auto Gear`. All of the following methods are found in `driveTrain.java`. `setAutoGear()` will enable/disable the auto gear mode. This will not control the auto gear but will allow it to be controlled. `useAutoGear(double tInput)` is what will be placed in either teleOp or auto. code, it will be given the current value of driving or the current position of the joystick. This will allow it to determine what gear to shift into. `setAutoGearPercent(double gearPercentCap)` is used to set the percent that determines when the auto gear is to shift into high gear at a certain negative/positive thrust (Default 75%). `setAutoGearInputRange(double minInput, double maxInput)` is used to tell the auto gear the maximum and minimum of driving value (Default -1,1). `getAutoGear()` will return whether the auto gear is enabled or not. This is a lot to understand, but it works. We will figure it out on Tuesday, just thought it was a feature we needed to implement.

**Comment by nhubbard** [comment]
@noahhusby For auto switching, I think it should. > .5 or -.5 speed should be high gear, and otherwise it should be lower.

**Comment by noahhusby** [comment]
@nhubbard That is the Gear Percent Cap, just do `setAutoGearPercent(50)` to change it in robot init.

**Comment by pguenthe** [comment]
This will need tweaking on the actual robot.  For one thing, keep in mind that the same motor speed in high gear is a lot faster than in low gear--we don't want the robot to suddenly lurch forward when the gear shifts, so there may need to be some code to ease that transition (ie drive the motors at a lower speed when it switches and ramp back up to the actual input.

I doubt we'll want an always high gear mode--we'll probably just want low gear and auto gear, so we could have a single switch or button, but we can see as we drive it.

**Comment by noahhusby** [comment]
@pguenthe Yup Agreed. I am not going to work on auto gear anymore until Justin and Paul work out any kinks with the gearboxes and the robot drives perfectly in low gear, this week I am going to start testing PID, as will @nhubbard probably, and that would get us working on autonomous. We just need to make sure all of our PID, navx, and gear methods are perfect before worrying about autonomous.

**Comment by nhubbard** [comment]
@pguenthe We added an autonomous program selector. The new `DriveForward` command will drive the robot forward, and will be used as a catch-all for any other autonomous modes. All it does is drive the robot forward for crossing the autonomous line.

**Comment by pguenthe** [comment]
Important lesson learned: Always build a failsafe into a method like DriveForward.  Don't just rely on the encoder--what if an encoder goes bad?--also have timeout code.

We learned this lesson by grinding four grooves with our wheels in Southfield High School's main gym floor a few years back when our autonomous never stopped because a sensor went bad.

**Comment by pguenthe** [comment]
@nhubbard et al for the Drivetrain, for usePIDOutput one way of doing it is something like
`drivetrain.arcadeDrive(moveSpeed, -output);`
where moveSpeed is a member variable of the Drivetrain set in various other methods (like TeleopDrive or some Autonomous mode).

With this setup we'll only use usePIDOutput when we want to drive straight... however, if we want to use PID to turn the robot to a precise angle we'll have to dig into it more and write some other method(s) that utilize returnPIDInput.

**Comment by nhubbard** [comment]
@pguenthe Are we using the NavX angle or some other value as the PID input?

**Comment by pguenthe** [comment]
The NavX angle

**Comment by nhubbard** [comment]
@pguenthe Noah just pushed 26a6dc58bf7180fd9a8a932ab828b70eb52275a8, which added our Autonomous chooser and our two programs for autonomous. We currently have the forward autonomous (only cross line for points) and default autonomous (experimental multi-target autonomous) uploaded.
