### ISSUE TITLE
Install Actual Documentation

### ISSUE THREAD

**Issue by nhubbard** [Robocubs/2018RobotCode#5]
This makes our project more maintainable and clear to use for others who wish to use it in the future.

* [x] Replace license with Markdown license.
* [x] Create an actual README that isn't 2 lines of Markdown.
* [ ] Javadoc-certify each file (this is a long, annoying task)

Feel free to comment on this task.

**Comment by pguenthe** [comment]
Documentation is good.  Attempting to do it through Javadoc is good.  Investing a lot of time to javadoc-certify it should be a much, much lower priority during a tight build and competition season.

**Comment by nhubbard** [comment]
Just now pushed eb433e9497c5b36c563b7e9f1cc86f9374e3d4da, which crosses off the first two tasks.
@pguenthe Indeed, I am making a new project called "Tasks on the Backburner", which will house this and other small projects that are distracting from build season.
