### ISSUE TITLE
Clean up subsystems & implement state machines

### ISSUE THREAD

**Issue by pguenthe** [Robocubs/2018RobotCode#6]
A few minor observations about code readability and conciseness.

Going through the code (in the `DropOffScaleHigh`), I found `Robot.liftArm.getArmAngle() > scaleHighHeight && Robot.liftArm.getArmAngle() != scaleHighHeight`. The > operator automatically excludes equality, so the second half of the compound (after the &&) is redundant.

- [x] **Solution**: Simplify the statement in `DropOffScaleHigh` to `Robot.liftArm.getArmAngle() > scaleHighHeight`. Please keep a lookout for these statements in the future. Nice catch, Mr. Guenther! **Completed as of commit 854f3465f973d416308ee6062b9e51e8e251afa2.**

---

I like where you're going with the `x = 0`, `x = 1` in this command; this is the start of a [*state machine*](https://www.google.com/search?q=state+machine+definition).  I'd suggest using an [*enum*](https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html) for the various states so that it's even easier to follow, and better variable names than `x` (which is very generic).  When you get the wrist and other joints fully implemented, this is going to be even more important.  Relevant lines for an example:

```java
private final int MOVING = 0;
private final int REACHED = 1;
// ...
private int armState = MOVING;
//...
while (armState == MOVING) {
//...
} else {
armState = REACHED;
}
```

See also this [more fully realized example of a team using an enum in a state machine](https://github.com/RobotsByTheC/CMonster2015/blob/master/src/org/usfirst/frc/team2084/CMonster2015/subsystems/ContainerHookSubsystem.java)

- [x] **Solution**: Implement a state machine in the Arm classes. It will make a very readable improvement. Thanks, Mr. Guenther!

***Important!*** You can Google some tutorials and videos on State Machines if you'd like to know more.  Note that the State Design Pattern is not exactly the same as the State Machine and is not what we want here.

**Edit**: Feb 1, 2018 11:37 by @nhubbard: Converted to task list for management purposes.

**Comment by nhubbard** [comment]
@pguenthe Which class do you want us to implement the state machine in? I'm having trouble finding which class you're referencing.

**Comment by pguenthe** [comment]
This issue is referencing DropOffScaleHigh but state machines would be useful for many of our commands.  (I should've said commands rather than subsystems in the title.)

**Comment by nhubbard** [comment]
Just curious, what is that command even doing? A state machine may even be overkill in this case. I would refactor it to something like this, but I don't know how this works.

---
```java
public class DropOffScaleHigh extends Command {
    public double scaleHighHeight = 0.0; // This is the number that the arm angle is at when it has reached the scale height.
    public double currentHeight; // This is the current height.
    protected void initialize() {
        currentHeight = Robot.liftArm.getArmAngle();
    }
    protected void execute() {
        do {
            currentHeight = Robot.liftArm.getArmAngle();
        } while (currentHeight < scaleHighHeight);
        // Use the winch to stop the lift.
    }
}
```

**Comment by pguenthe** [comment]
This command isn't done.  I don't know the full pseudocode but it's going to have to position multiple things in stages--get the arm to the target angle, then get the wrist to the right angle, then release the clamp and/or punch the puncher.

Although if we're going with a button to first get into the right position to drop off, and then a button to drop, it's the positioning command which will be more important.

**Comment by nhubbard** [comment]
We have simplified the commands and made this second part irrelevant.
