### ISSUE TITLE
Testing Functionality for MVP (Minimum Viable Product)

### ISSUE THREAD

**Issue by nhubbard** [Robocubs/2018RobotCode#8]
Convert from the post on Band.

| Icon                   | Type This...             | Meaning           |
|------------------------|--------------------------|-------------------|
| :large_blue_diamond:   | `:large_blue_diamond:`   | Low Priority      |
| :large_orange_diamond: | `:large_orange_diamond:` | Medium Priority   |
| :red_circle:           | `:red_circle:`           | High Priority     |
| :bangbang:             | `:bangbang:`             | Immediate Concern |
---

**Driver Functionality: Movement**
* [x] Forward and backward :red_circle:<br>*Moving the robot forwards and backwards manually.*<br>**Signed off by:** Nicholas Hubbard on `Friday, February 16, 2018`
* [x] Rotation :red_circle:<br>*Rotating the robot in up to 360° of freedom.*<br>**Signed off by:** Nicholas Hubbard on `Friday, February 16, 2018`
* [x] High gear graceful stop :large_blue_diamond:<br>*Read the gear selection. Based on this, gracefully stop in high gear; **dead stop in low gear only**.*<br>**Signed off by:**

**Driver Functionality: Gear Shifting**
* [x] Low Gear :large_orange_diamond:<br>*Run the drivetrain at low gear with a manual button press.*<br>**Signed off by:** Nicholas Hubbard on `Saturday, February 17, 2018`
* [x] High Gear :large_orange_diamond:<br>***This is not user selectable!** Run the drivetrain at high gear.*<br>**Signed off by:** Nicholas Hubbard on `Saturday, February 17, 2018`
* [x] Automatic Gear :large_blue_diamond:<br>*Shifting to high or low based on the speed the robot is running at. Start a count of rotations on `teleopInit()`. After `x` amount of rotations, shift to high gear if low gear is not manually chosen. On stick release, reset the counter.*<br>**Signed off by:**

**Operator Functionality: Arm and Wrist**
* [x] Raising and lowering arm stick :red_circle:<br>***This is not user selectable!** Set the arm stick to a specified position. There will be presets for this.*<br>**Signed off by:** Noah Husby on `Thursday, February 15, 2018`
* Arm and wrist movement
    * [x] Move to floor position :large_orange_diamond:<br>*For picking up cubes off of the floor.*<br>**Signed off by:** Noah Husby, `Sunday, February 18, 2018`
    * [x] Move to switch delivery position :large_orange_diamond:<br>*For delivering cube to switch.*<br>**Signed off by:** Noah Husby, `Sunday, February 18, 2018`
    * [x] Move to scale delivery position :large_orange_diamond:<br>*For delivering cube to scale. Close the wrist if not already closed.*<br>**Signed off by:** Noah Husby, `Sunday, February 18, 2018`
    * [x] Move to cube storage delivery position :large_orange_diamond:<br>*For delivering cube to vault.*<br>**Signed off by:** Noah Husby, `Sunday, February 18, 2018`
    * [x] Move to custom delivery position :large_orange_diamond:<br>*For pyramid/missed drop/et cetera.*<br>**Signed off by:** Noah Husby, `Sunday, February 18, 2018`
    * [x] Rotation of wrist :large_orange_diamond:<br>*For movement of the wrist to **any given angle**. Crucial to custom delivery position.*<br>**Signed off by:** Nicholas Hubbard on `Saturday, February 17, 2018`

**Operator Functionality: Buttons**
* Cube dropping positions
    * [x] Drop the cube naturally :red_circle:<br>*Drop a cube directly over the target.*<br>**Signed off by:** Nicholas Hubbard on `Saturday, February 17, 2018`
    * [x] Drop the cube with **W O O S H** :red_circle:<br>*Drop a cube with a punt from the puncher.*<br>**Signed off by:** Nicholas Hubbard on `Saturday, February 17, 2018`
* [x] Climb Position :bangbang:<br>*Release the wrist and winch brake, close the hand, raise the arm to the climbing angle, and rotate the wrist to the climbing position. Set winch and wrist brakes when done.*<br>**Signed off by:** Nicholas Hubbard, `February 20, 2018`
* [x] Climbing :bangbang:<br>**Does not engage unless the robot is already in climbing position!** Release the winch and wrist brakes, and rotate the wrist the engage the rung. Activate the winch to climb and set the winch brake at the end of the climb. Do **not** set the wrist brake. **Must absolutely be able to halt the climb!***<br>**Signed off by:** Nicholas Hubbard, `February 20, 2018`
* [x] Pre-match position :red_circle:<br>*Load a cube into position for starting a match.*<br>**Signed off by:** Nicholas Hubbard on `Saturday, February 17, 2018`
* [x] Puncher :red_circle:<br>*Moving the puncher inward and outward.*<br>**Signed off by:** Nicholas Hubbard on `Saturday, February 17, 2018`

**Robot Status Functions**
* [x] Gear status :red_circle:<br>*Low or high gear?*<br>**Signed off by:** Nicholas Hubbard, `Saturday, February 17, 2018`
* [x] Gear selection status :red_circle:<br>*Low or automatic?*<br>**Signed off by:** Noah Husby, `Thursday, Februrary 22, 2018`
* [x] Distance traveled since last dead stick :red_circle:<br>*Count the distance of the drive counter since the last time the stick was neutral.*<br>**Signed off by:**
* [x] Arm position :red_circle:<br>*Retrieved by potentiometer.*<br>**Signed off by:** Noah Husby, `Thursday, Februrary 22, 2018`
* [x] Wrist position :red_circle:<br>*Retrieved by encoder.*<br>**Signed off by:** Noah Husby, `Thursday, Februrary 22, 2018`
* [x] Direction of rotation to wrist position :red_circle:<br>*This is what direction the wrist was rotated to get to a position.*<br>**Signed off by:** Noah Husby, `Thursday, Februrary 22, 2018`
* [x] Gripper status :bangbang:<br>*Read the arm position. **Safety measure for wrist rotation. Blocking level of priority!***<br>**Signed off by:** Noah Husby, `Thursday, Februrary 22, 2018`

**Goals**
Automate as much as possible for the operator!

**Comment by pguenthe** [comment]
Changed drop commands to reflect desire to have drop with and without punch.

**Comment by nhubbard** [comment]
@pguenthe @noahhusby I'm closing this issue for now, since we have all of the items down. Let me know, should we need to reopen it.
